### ISSUE TITLE
Webpack

### ISSUE THREAD

**Issue by fxdave** [yosbelms/cor#19]
Hi I like this language.
Can you make description for using Cor with Webpack?

**Comment by yosbelms** [comment]
Hey @fxdave, actually, you can use the compile command, the command `cor compile ./src` will write a `.js` file per each `.cor` file, the other thing you need is webpack watching `.js` files

See: http://yosbelms.github.io/cor/docs/documentation.html#compile for command reference

**Comment by fxdave** [comment]
Awesome, thanks!
